proposal file structure
DevInnovationLab/guides pull request #24
Opened 2023-09-06 08:43 UTC by axlehner

first shot proposal. material still in `s-ICC`

2023-09-14 15:16 UTC, wwiecek commented
@axlehner I am okay with whatever file structure works for you. But where should I review these materials? Will you push them into this repository next?

2023-09-14 19:19 UTC, luizaandrade requested changes
Hi @axlehner , I have made some suggestions based on our chat. Happy to iterate over these.

2023-09-14 19:19 UTC, luizaandrade commented on README.md
> +│   │	│   ├── examples/   	# Example code MHT
```suggestion
```

2023-09-14 19:19 UTC, luizaandrade commented on README.md
> +gh-pages branch       # DIL Analytics Manual
```suggestion
gh-pages branch       # DIL Analytics Manual
├── Principles of Analytics
├── Coding Guides # Detailed articles with general code snippets
│   |── Power calculations/ 	#
│   │   ├── Covariates
│   │   ├── ICC      	
│   │   ├── Panel RCT
│   │   ├── stratification
│   │   ├── Multiple Hypotheses Testing
├── DIL templates
├── External resources

```

2023-09-14 19:19 UTC, luizaandrade commented on README.md
> +│   ├── examples/     	# Example documents with replication that showcase power calculations from past DIL projects
```suggestion
│   ├── examples/     	# Example documents with replication that showcase power calculations from past DIL projects
│   │   ├── power_calc/
│   │   │   ├── covariates.R
│   │   │   ├── icc.R
│   │   │   ├── panel_rct.R
│   │   │   ├── stratification.R
│   │   │   ├── mht.R
```

2023-09-18 20:14 UTC, luizaandrade approved these changes

2023-09-18 20:16 UTC, merged